### PR TITLE
Added pw change

### PR DESCRIPTION
**Pull request by jonpage**
This change turns on the registerable devise feature.

### CODE REVIEW

**Comment by jonpage** [comment]
Before this gets merged we should add a link to users/edit so users know how to change their password.

**Comment by kotodharma** [comment]
I honestly have no clue how these are the changes to allow users to change their password. It's not at all the sort of thing I expected to see. Should I trust you and approve it? :=)

**Comment by kotodharma** [comment]
Just noticed your comment above about adding a link

**Comment by jonpage** [comment]
It's the magic of devise

**Pull request merged**
