### PR TITLE
Add sheet_override to data_source_downloads (UA-169)

### PR DESCRIPTION
**Pull request by kotodharma**
Most of the top half of the diffs screen is "clean-up" stuff, not functionally related to this story. The meat is in the bottom half.

### CODE REVIEW

**Comment by jonpage** [comment]
Are there any recommended testing steps?

**Comment by kotodharma** [comment]
Could you explain more explicitly what situation you're referring to re: line 25? (to make sure we're on the same page). The only thing I can think of is that the worksheet might be cached at the time when someone updates the DSD to add a new override to it (I don't think we worry about one override being changed to another, do we?). In that case, the change will not be noticed until the system is restarted. Is that the case you're talking about?

**Comment by jonpage** [comment]
The `sheet_key` should probably include the `sheet_override`.

**Comment by kotodharma** [comment]
Re: testing: Based on the observation that spreadsheet data are always read via the DownloadsCache, which creates Roo objects for worksheets and caches them in the Rails.cache, as long as we confirm that the correct worksheet is being read and cached by that class, things should be working. In dev environment, console logs will show which handles/sheets are being read and written to Rails.cache. I chose a data source with a wildcard handle (212542) that had a couple of DSD records requiring override, and set the overrides accordingly in the db (JUL and DEC in 2015). Running reload_source() against this data source allows you to see which sheets are being processed.

**Comment by kotodharma** [comment]
The concern about picking up override values and including them in cache keys should now be addressed.

**Pull request merged**
